### ISSUE TITLE
Please be a joke

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [jonschlinkert/is-even#1]
^

**Comment by jonschlinkert** [comment]
modular, unit-testable, reliable code is nothing to joke about ;)

**Comment by MegaApuTurkUltra** [comment]
but is it webscale?

**Comment by jonschlinkert** [comment]
what does "webscale" mean? It seems like I only get questions like this from people who have zero experience maintaining projects that anyone uses. 

Sounds like you're just learning about programming. My advice is that you take notes and observe, instead of acting like the rest of your generation and assuming you know what's up.

**Comment by jonschlinkert** [comment]
Ironically, [this issue](https://github.com/jonschlinkert/is-even/issues/2) exemplifies why code like this should be generalized into modules. It's not always as simple as it looks to get a "correct" value.
